/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameRoot from "./GameRoot"
import UICtrl from "./UICtrl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="GameRoot.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("GameRoot.ts",GameRoot);
        reg("UICtrl.ts",UICtrl);
    }
}
GameConfig.init();